/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ClienteControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author JuanGabriel
 */
public class iniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form iniciarSesion
     */
    public iniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        lblUsuarioI = new javax.swing.JLabel();
        lblContraseniaI = new javax.swing.JLabel();
        txtUsuariol = new javax.swing.JTextField();
        txtContrasenial = new javax.swing.JPasswordField();
        InicioSesion = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciar.setBackground(new java.awt.Color(204, 204, 204));
        btnIniciar.setText("Iniciar sesion");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        lblUsuarioI.setText(" Usuario");
        jPanel1.add(lblUsuarioI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 436, -1));

        lblContraseniaI.setText("Contraseña sesion");
        jPanel1.add(lblContraseniaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, 22));

        txtUsuariol.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtUsuariol, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 160, -1));

        txtContrasenial.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtContrasenial, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 160, -1));

        InicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/inicioSesion.png"))); // NOI18N
        jPanel1.add(InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 100, 100));

        btnVolver.setBackground(new java.awt.Color(153, 153, 153));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        ClienteControlador clienteControlador=new ClienteControlador();
        String usu=txtUsuariol.getText();
        String pass=new String(txtContrasenial.getPassword());
        if (clienteControlador.validarCliente(usu, pass)){
            gestionPedidos pagar= new gestionPedidos();
            pagar.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Error en el usuario y/o contraseña");
        }
        
     
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        RegistroUsuarioVista Usuario = new RegistroUsuarioVista();
        Usuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InicioSesion;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseniaI;
    private javax.swing.JLabel lblUsuarioI;
    private javax.swing.JPasswordField txtContrasenial;
    private javax.swing.JTextField txtUsuariol;
    // End of variables declaration//GEN-END:variables
}
